# Uncomment the next line to define a global platform for your project
  platform :ios, '8.0'

target 'BaseProject_OC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

   pod 'WebViewJavascriptBridge', '~> 6.0.3'
   pod 'dsBridge'

  pod 'DateTools', '~> 2.0.0'


   pod 'Masonry', '~> 1.1.0'

  target 'BaseProject_OCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaseProject_OCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
